#!/command/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

source /usr/local/bin/env-helpers.sh

load_generated_env
configure_bundled_mailpit_env

wait_for_postgres_ready
wait_for_redis_ready
wait_for_mailpit_ready

/usr/local/bin/bootstrap-infisical.sh &

export HOME="/home/non-root-user"
export USER="non-root-user"
export LOGNAME="non-root-user"
export PATH="/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

exec /command/s6-setuidgid non-root-user /bin/sh -c 'cd /backend && exec ./standalone-entrypoint.sh'
